<?php

use Illuminate\Database\Seeder;

class seeder_tabla_producto extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $producto = [
            [
                'AUBN',
                'Auricular',
                'Bluetooth',
                'S/M',
                'Bluetooth',
                'Negro',
                '20',
                '120',
                '1',
            ],
            [
                'AUBB',
                'Auricular',
                'Bluetooth',
                'S/M',
                'Bluetooth',
                'Blanco',
                '20',
                '120',
                '1',
            ],
            [
                'CI566P',
                'Cable',
                'USB',
                'Apple',
                'Iphone 5/6/6plus',
                'Negro',
                '10',
                '30',
                '1',
            ],
            [
                'CI566PB',
                'Cable',
                'USB',
                'Apple',
                'Iphone 5/6/6plus',
                'Blanco',
                '10',
                '30',
                '1',
            ],
            [
                'CI566PR',
                'Cable',
                'USB',
                'Apple',
                'Iphone 5/6/6plus',
                'Rosa',
                '10',
                '30',
                '1',
            ],
            [
                'CI566PA',
                'Cable',
                'USB',
                'Apple',
                'Iphone 5/6/6plus',
                'Azul',
                '10',
                '30',
                '1',
            ],
            [
                'CI566PM',
                'Cable',
                'USB',
                'Apple',
                'Iphone 5/6/6plus',
                'Morado',
                '10',
                '30',
                '1',
            ],
            [
                'CV8N',
                'Cable',
                'USB',
                'S/M',
                'S/M',
                'Negro',
                '10',
                '30',
                '1',
            ],
            [
                'CV8B',
                'Cable',
                'USB',
                'S/M',
                'S/M',
                'Blanco',
                '10',
                '30',
                '1',
            ],
            [
                'CV8R',
                'Cable',
                'USB',
                'S/M',
                'S/M',
                'Rosa',
                '10',
                '30',
                '1',
            ],
            [
                'CV8A',
                'Cable',
                'USB',
                'S/M',
                'S/M',
                'Azul',
                '10',
                '30',
                '1',
            ],
            [
                'CV8M',
                'Cable',
                'USB',
                'S/M',
                'S/M',
                'Morado',
                '10',
                '30',
                '1',
            ],
            [
                'FUR1G',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'Grand Prime',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2G',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'Grand Prime',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3G',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'Grand Prime',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4G',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'Grand Prime',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5G',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'Grand Prime',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6G',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'Grand Prime',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7G',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'Grand Prime',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1J',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J3 2018',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2J',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J3 2018',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3J',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J3 2018',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4J',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J3 2018',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5J',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J3 2018',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6J',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J3 2018',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7J',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J3 2018',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1J7',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J7',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2J7',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J7',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3J7',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J7',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4J7',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J7',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5J7',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J7',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6J7',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J7',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7J7',
                'Funda',
                'Uso rudo',
                'SAMSUNG',
                'J7',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1XS',
                'Funda',
                'Uso rudo',
                'LG',
                'X Screen',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2XS',
                'Funda',
                'Uso rudo',
                'LG',
                'X Screen',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3XS',
                'Funda',
                'Uso rudo',
                'LG',
                'X Screen',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4XS',
                'Funda',
                'Uso rudo',
                'LG',
                'X Screen',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5XS',
                'Funda',
                'Uso rudo',
                'LG',
                'X Screen',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6XS',
                'Funda',
                'Uso rudo',
                'LG',
                'X Screen',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7XS',
                'Funda',
                'Uso rudo',
                'LG',
                'X Screen',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1XT',
                'Funda',
                'Uso rudo',
                'LG',
                'X Style',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2XT',
                'Funda',
                'Uso rudo',
                'LG',
                'X Style',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3XT',
                'Funda',
                'Uso rudo',
                'LG',
                'X Style',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4XT',
                'Funda',
                'Uso rudo',
                'LG',
                'X Style',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5XT',
                'Funda',
                'Uso rudo',
                'LG',
                'X Style',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6XT',
                'Funda',
                'Uso rudo',
                'LG',
                'X Style',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7XT',
                'Funda',
                'Uso rudo',
                'LG',
                'X Style',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1XP',
                'Funda',
                'Uso rudo',
                'LG',
                'X Power',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2XP',
                'Funda',
                'Uso rudo',
                'LG',
                'X Power',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3XP',
                'Funda',
                'Uso rudo',
                'LG',
                'X Power',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4XP',
                'Funda',
                'Uso rudo',
                'LG',
                'X Power',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5XP',
                'Funda',
                'Uso rudo',
                'LG',
                'X Power',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6XP',
                'Funda',
                'Uso rudo',
                'LG',
                'X Power',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7XP',
                'Funda',
                'Uso rudo',
                'LG',
                'X Power',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1P8',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P8 Lite',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2P8',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P8 Lite',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3P8',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P8 Lite',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4P8',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P8 Lite',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5P8',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P8 Lite',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6P8',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P8 Lite',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7P8',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P8 Lite',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1Y6',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'Y6II',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2Y6',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'Y6II',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3Y6',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'Y6II',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4Y6',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'Y6II',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5Y6',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'Y6II',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6Y6',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'Y6II',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7Y6',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'Y6II',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1P9',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P9',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2P9',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P9',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3P9',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P9',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4P9',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P9',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5P9',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P9',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6P9',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P9',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7P9',
                'Funda',
                'Uso rudo',
                'HUAWEI',
                'P9',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1I5',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 5C',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2I5',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 5C',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3I5',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 5C',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4I5',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 5C',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5I5',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 5C',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6I5',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 5C',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7I5',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 5C',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1I6',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 6 Plus',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2I6',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 6 Plus',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3I6',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 6 Plus',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4I6',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 6 Plus',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5I6',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 6 Plus',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6I6',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 6 Plus',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7I6',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 6 Plus',
                'Rosado',
                '50',
                '70',
                '1',
            ],
            [
                'FUR1I7',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 7',
                'Amarillo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR2I7',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 7',
                'Verde',
                '50',
                '70',
                '1',
            ],
            [
                'FUR3I7',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 7',
                'Azul Marino',
                '50',
                '70',
                '1',
            ],
            [
                'FUR4I7',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 7',
                'Negro',
                '50',
                '70',
                '1',
            ],
            [
                'FUR5I7',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 7',
                'Rojo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR6I7',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 7',
                'Azul Cielo',
                '50',
                '70',
                '1',
            ],
            [
                'FUR7I7',
                'Funda',
                'Uso rudo',
                'Apple',
                'Iphone 7',
                'Rosado',
                '50',
                '70',
                '1',
            ]
          ];
        $cont = count($producto);
        for ($i=0; $i < $cont ; $i++) {
            DB::table('producto')->insert([
              'referencia' => $producto[$i][0],
              'categoria_producto' => $producto[$i][1],
              'tipo_producto' => $producto[$i][2],
              'marca' => $producto[$i][3],
              'modelo' => $producto[$i][4],
              'color' => $producto[$i][5],
              'precio_compra' => $producto[$i][6],
              'precio_venta' => $producto[$i][7],
              'estatus' => $producto[$i][8],
            ]);
        }
    }
}
